sudo: false
language: node_js
node_js:
- "6"

cache:
  directories:
  - node_modules/

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/gcloud-credentials.json
    - TEST_BUCKET_NAME=big-sample
    - GCLOUD_PROJECT=big-sample

before_install:
  - openssl aes-256-cbc -K $encrypted_fdad1b470464_key -iv $encrypted_fdad1b470464_iv -in encrypted.tar.gz.enc -out encrypted.tar.gz -d
  - tar -xzf encrypted.tar.gz
  - npm install -g npm
  - npm set progress=false
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - gcloud auth activate-service-account --key-file gcloud-credentials.json

install: 
  - gcloud config set project big-sample
  - npm install

script:
  - glcoud app deploy --project big-sample